language: node_js
node_js:
- 'node'

env:
  - TEST_DIR=frontend
  - TEST_DIR=backend

install:
  - "npm i -g tslint typescript"
  - "cd $TEST_DIR && npm install"

script: tslint -p tsconfig.json -c tslint.json


