language: node_js
node_js:
- 'node'

env:
  - TEST_DIR=frontend
  - TEST_DIR=backend
  - DEBUG=true
  - DB_NAME=op-dev;
  - NODE_ENV=development
  - PORT=5000

services: mongodb

install:
  - "npm i -g tslint typescript"
  - "cd $TEST_DIR && npm install"

script: tslint -p tsconfig.json -c tslint.json


